SOURCES := $(wildcard *.cc)
HEADERS := $(wildcard *.hh)
OBJECTS := $(patsubst %.cc,%.o,$(SOURCES))
DEPS    := $(patsubst %.cc,%.d,$(SOURCES))

LIBMFILE_CFLAGS  = # e.g. -I/usr/local/include
LIBMFILE_LDFLAGS = # e.g. -L /opt/lib64

LIBX11_CFLAGS = # e.g. -I/opt/X11/include
LIBX11_LDFLAGS = # e.g. -L/opt/X11/lib

ROOT_CONFIG = root-config
ROOT_CLING  = rootcling

ROOT_CLING_FLAGS  = -f $@ -noIncludePaths -inlineInputHeader
ROOT_CLING_FLAGS += -s $(TARGET) -rmf $(ROOTMAP)
# Removed as a precaution, failed in fit
# ROOT_CLING_FLAGS += -rml lib$(MODNAME).so

ROOT_CXXFLAGS := $(shell $(ROOT_CONFIG) --cflags)
ROOT_LIBS     := $(shell $(ROOT_CONFIG) --libs)
ROOT_GLIBS    := $(shell $(ROOT_CONFIG) --glibs)

CFLAGS       = -O2 -g -Wall -fPIC $(DEPFLAGS)
CXXFLAGS     = $(ROOT_CXXFLAGS) -Wall -g -O2 -fPIC $(DEPFLAGS)
LDFLAGS      = -shared
LDLIBS       = -lstdc++
DEPFLAGS     = -MT $@ -MMD -MP -MF $*.Td
POSTCOMPILE  = mv -f $*.Td $*.d

TARGET   = lib$(MODNAME).so
ROOTDICT = $(MODNAME)_rdict.cc
ROOTMAP  = lib$(MODNAME).rootmap
