#!/usr/bin/env python
# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------------
# This is the main HDTV application.
#-------------------------------------------------------------------------------

# Load required modules
import sys
import os.path
import ROOT

# Get ~/.hdtv directory
hdtvpath = os.path.expanduser("~/.hdtv")
if not os.path.exists(hdtvpath):
	raise RuntimeError, "Failed to load core plugins: directory ~/.hdtv not found."

# Set the python path
sys.path.append(hdtvpath)
sys.path.append(hdtvpath + "/plugins")

# Import core modules
import hdtv.dlmgr
hdtv.dlmgr.path.append(hdtvpath + "/lib")
import hdtv.cmdline
hdtv.cmdline.SetReadlineHistory(hdtvpath + "/hdtv_history")
hdtv.cmdline.SetInteractiveDict(locals())
# import hdtv.config

from hdtv.window import Window
from hdtv.drawable import DrawableCompound

from specInterface import SpecInterface
from fitInterface import FitInterface

window = Window() 
spectra = DrawableCompound(window.fViewport)

s = SpecInterface(window, spectra)

f = FitInterface(window, spectra)

# for debugging
#s.LoadSpectra('/home/tanja/hdtv/test/spectra/231Th*.ascii')
s.LoadSpectra('/home/tanja/hdtv/test/spectra/60*')

# Go
hdtv.cmdline.MainLoop()

