/********************************************************************
* lc2dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error lc2dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablelc2dict();
extern void G__cpp_setup_inheritancelc2dict();
extern void G__cpp_setup_typetablelc2dict();
extern void G__cpp_setup_memvarlc2dict();
extern void G__cpp_setup_globallc2dict();
extern void G__cpp_setup_memfunclc2dict();
extern void G__cpp_setup_funclc2dict();
extern void G__set_cpp_environmentlc2dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LC2Reader.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__lc2dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__lc2dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__lc2dictLN_TH1;
extern G__linked_taginfo G__lc2dictLN_lc_header;
extern G__linked_taginfo G__lc2dictLN_lc_poslen;
extern G__linked_taginfo G__lc2dictLN_LC2Reader;

/* STUB derived class for protected member access */
