# Common defines for Makefiles below src/
CPP=g++
CC=gcc
ROOTCINT=rootcint
INCL_PATH=-I/ikpv2/include
CFLAGS=$(shell root-config --cflags) $(INCL_PATH) -Wall -g
LFLAGS=$(shell root-config --glibs)
DESTDIR=../../hdtv/clib
