# Common defines for Makefiles below src/
PREFIX=/ikpv2

CPP=g++
CC=gcc
ROOTCINT=rootcint
INCL_PATH=$(PREFIX)/include
CFLAGS=$(shell root-config --cflags) -I$(INCL_PATH) -Wall -g
LFLAGS=$(shell root-config --glibs)
DESTDIR=../../hdtv/clib
